Devel/rbtree
crash-python/crash-python pull request #39
Opened 2019-06-27 16:34 UTC by Werkov

2019-06-27 20:35 UTC, jeffmahoney requested changes
There are a few nits, comments inline, but also (as you mentioned on IRC) since this is intended to be part of the API, we need documentation for it.  We also need test cases. If you can come up with simple cases like those in tests/test_list.py, that would be helpful.  Test cases that work with common in-kernel rbtrees would also be helpful to ensure that it still works correctly when the kernel is updated.

Finally, outside of the .gitignore changes, this should all be a single commit.

Thanks,

-Jeff

2019-06-27 20:35 UTC, jeffmahoney commented on crash/types/rbtree.py
> +        raise ArgumentTypeError('root', root, types.rb_root_type)
This should be UnexpectedGDBTypeError now.

2019-06-27 20:35 UTC, jeffmahoney commented on crash/types/rbtree.py
> +        raise InvalidArgumentError("root must be gdb.Value representing 'struct rb_root' or 'struct rb_root *' not {}"
This should be ArgumentTypeError now

2019-06-28 15:16 UTC, Werkov commented
No ready yet (only backing up the branch), will rebase later.

2019-07-02 14:02 UTC, Werkov commented
Force pushed a new version:
- rebased onto current master,
- added unit and dump tests,
- squashed altogether.

Also, I noticed that similar API for linked list traversing says in the docs:

> def list_for_each
>         [...]
>         gdb.Value: The next node in the list.  The value is
>         of type ``struct list_head``.

However, the returned gdb.Value is of type `struct list_head *`, i.e. the docs isn't consistent with the implementation. The rbtree implementation honors the docs. Let me know which is the preferred way for these iterators (I expect the non-pointer variant).

2020-07-08 10:55 UTC, Werkov commented
I've rebased the branch on the current master (resolved trouble with gdb update from 8.3 to 9.1) and added one more commit to rectify the type situation as laid out in my previous comment.
AFAICT, all the remarks should be resolved now.

2020-11-17 15:31 UTC, merged